Repository scoala-online/demo-project, pull requests merged in 2021-02, with the labels that each got.

#4 test: 💍 Edit readme
  README.md
Labels: test 💍

#8 Ci/#5 setup automated lint workflow
  .github/workflows/lint.yml
  apps/react-app/src/app/App.test.js
  package-lock.json
  package.json
Labels: ci 🎡

#12 fix: 🐛 linting script in package.json
  package.json
Labels: ci 🎡, fix 🐛

#11 ci: 🎡 add automated format checking workflow
  .github/workflows/format.yml
  README.md
  apps/react-app/src/app/App.js
  apps/react-app/src/app/App.test.js
  apps/react-app/src/app/component/studentCreate.component.js
  apps/react-app/src/app/component/studentList.component.js
  apps/react-app/src/app/component/studentUpdate.component.js
  apps/react-app/src/app/reportWebVitals.js
  apps/react-app/src/app/services/httpService.js
  workspace.json
Labels: ci 🎡

#13 Ci/#7 setup automated test workflow
  .github/workflows/test.yml
  apps/react-app/src/app/App.test.js
  apps/react-app/src/app/old shit/app.js
  apps/react-app/src/app/old shit/app.module.css
  apps/react-app/src/app/old shit/app.spec.js
  apps/react-app/src/app/old shit/logo.svg
  apps/react-app/src/app/old shit/star.svg
  package-lock.json
  package.json
Labels: ci 🎡, test 💍

#15 Fix/#14 test issue
  apps/react-app/src/app/App.js
  apps/react-app/src/app/components/studentCreate.component.js
  apps/react-app/src/app/components/studentList.component.js
  apps/react-app/src/app/components/studentUpdate.component.js
Labels: fix 🐛

#17 style: 💄 changed style of buttons :))
  apps/react-app/src/app/components/studentList.component.js
Labels: style 💄

#21 fix: 🐛 Fix 'Update' and 'Add new Student' buttons
  apps/react-app/src/app/components/studentCreate.component.js
  apps/react-app/src/app/components/studentUpdate.component.js
Labels: fix 🐛
